Экзамен
KiberDron/2022-2-VK-EDU-FS-Frontend-A-Murygin pull request #12
Opened 2022-12-29 17:30 UTC by KiberDron

# Экзамен

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Критерии:
* В корневой папке репозитория создать базовое приложение exam с помощью [CRA (https://github.com/facebook/create-react-app#quick-overview) по инструкции выше
* Сверстать 2 страницы и необходимые компоненты. Использовать стили
* Реализовать перевод с одного языка на другой (хорошо, если можно будет выбрать язык из выпадающего списка)
* Реализовать перевод с неизвестного языка (автоопределитель из API)
* Сохранять историю переводов в localStorage
* Использовать Redux
* Использовать React-router для перехода между страницами
* Задеплоить решение, используя GitHub Actions.
* Теория: Объяснить, почему были использованы те или иные инструменты, участки кода и механизмы при решении задачи. Ответить на теоретические вопросы (пункт выполняется лично с преподавателем)
* Ревью: получить правки по коду и исправить их (получаются лично у преподавателя и выполняются самостоятельно)

2022-12-29 18:28 UTC, HaseProgram commented on exam/src/components/HistoryButton/HistoryButton.jsx
> +                <button className={classes.back_button} type="">
Убрать <button>

2022-12-29 18:31 UTC, HaseProgram commented on exam/src/pages/PageMain/PageMain.jsx
> +            .then(response => setOutput(response[0].translations))
response[0].translations[0].text

2022-12-29 18:32 UTC, HaseProgram commented on exam/src/pages/PageMain/PageMain.jsx
> +            .then(response => setOutput(response[0].translations))
Вернуть

2022-12-29 18:48 UTC, HaseProgram requested changes, later dismissed
Доделать пункты + вернуть фетч. По готовности тэгнуть на финальную проверку

2022-12-30 07:48 UTC, KiberDron commented
Все замечания исправил плюс доделал недостающие пункты (кроме редакса, его не использовал). Приложение задеплоил на `GitHub Pages`. По идее все должно работать корректно, но если вдруг понадобится, могу записать гифку, подтверждающую работу приложения.

2022-12-31 12:11 UTC, martinkomitsky approved these changes
36

На  выходных можно досдать  оставшиеся  домашки и получить 4.

2022-12-31 12:11 UTC, merged