ДЗ 5
KiberDron/2022-2-VK-EDU-FS-Frontend-A-Murygin pull request #6
Opened 2022-11-10 20:47 UTC by KiberDron

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
*
*
*

2022-11-11 20:18 UTC, martinkomitsky commented on react-chat/src/index.js
> +import { BrowserRouter } from 'react-router-dom'
зачем в этом ДЗ react-router?

2022-11-11 20:21 UTC, martinkomitsky commented on react-chat/index.html
> +<!DOCTYPE html>
ненужный файл, удалить

2022-11-11 20:22 UTC, martinkomitsky commented on react-chat/public/index.html
> +    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
можно заменить на библиотечные иконки

2022-11-11 20:23 UTC, martinkomitsky commented on react-chat/src/pages/PageChat/PageChat.jsx
> +        let messages = localStorage.getItem("messages") || "[]";
```suggestion
        const messages = localStorage.getItem("messages") || "[]";
```

2022-11-11 20:23 UTC, martinkomitsky commented on react-chat/src/pages/PageChat/PageChat.jsx
> +        let message = {
```suggestion
        const message = {
```

2022-11-11 20:26 UTC, martinkomitsky commented on react-chat/src/pages/PageChat/PageChat.jsx
> +            document.location.reload(true);
зочем :((( не нужно так делать в реакте, плз.
Лучше переиграй обновлением через стейт

2022-11-11 20:28 UTC, martinkomitsky requested changes
Нужно пофиксить несколько комментов

2022-11-11 20:44 UTC, martinkomitsky requested changes
Нужно исправить замечания

2022-11-11 20:44 UTC, martinkomitsky commented on react-chat/src/pages/PageChat/PageChat.jsx
> +        let savedMessages = getMessagesFromLocalStorage();
```suggestion
        const savedMessages = getMessagesFromLocalStorage();
```

2022-11-11 20:44 UTC, martinkomitsky commented on react-chat/src/pages/PageChat/PageChat.jsx
> +    useEffect(loadMessages, []);
открой секрет, пожалуйста, почему почти у всех в 5 ДЗ этот участок кода 1 в 1?)

2022-11-13 14:43 UTC, KiberDron commented on react-chat/public/index.html
> +    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
Не понял что имеется в виду

2022-11-13 14:43 UTC, KiberDron commented on react-chat/src/pages/PageChat/PageChat.jsx
> +        let messages = localStorage.getItem("messages") || "[]";
Там ведь дальше идет переопределение, поэтому let

2022-11-13 19:19 UTC, martinkomitsky commented on react-chat/public/index.html
> +    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/14847018/201540050-c15e958f-299b-4a63-bafe-a25c36d886a9.png">

2022-11-13 19:23 UTC, martinkomitsky requested changes
Остаются актуальными вопросы:
* https://github.com/KiberDron/2022-2-VK-EDU-FS-Frontend-A-Murygin/pull/6#discussion_r1020536753
* https://github.com/KiberDron/2022-2-VK-EDU-FS-Frontend-A-Murygin/pull/6#discussion_r1020547324

2022-11-13 21:35 UTC, KiberDron commented on react-chat/public/index.html
> +    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
Заменил

2022-11-13 21:36 UTC, KiberDron commented on react-chat/src/pages/PageChat/PageChat.jsx
> +    useEffect(loadMessages, []);
Не знаю, наверное коллективный разум)

2022-11-19 18:54 UTC, martinkomitsky approved these changes
12

2022-11-19 18:54 UTC, merged